install.packages("sparklyr", repos='http://cran.us.r-project.org')
install.packages("ggplot2", repos='http://cran.us.r-project.org')
install.packages("gridExtra", repos='http://cran.us.r-project.org')
install.packages("rmarkdown", repos='http://cran.us.r-project.org')
install.packages("knitr", repos='http://cran.us.r-project.org')
install.packages("formatR", repos='http://cran.us.r-project.org')
install.packages("tidyr", repos='http://cran.us.r-project.org')
install.packages("bigmemory", repos='http://cran.us.r-project.org')
install.packages("biganalytics", repos='http://cran.us.r-project.org')
install.packages("ff", repos='http://cran.us.r-project.org')
install.packages("ffbase", repos='http://cran.us.r-project.org')
install.packages("biglm", repos='http://cran.us.r-project.org')
#install.packages("ggmap", repos='http://cran.us.r-project.org', dependencies=TRUE)
